In [6]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

<bound method NDFrame.head of       engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759
1                     130            5.0        97.0     3149.664934
2                     170            NaN        78.0     3079.038997
3                     220            4.0         NaN     2542.392402
4                     210            1.0       140.0     3460.870990
...                   ...            ...         ...             ...
9699                  140            5.0       164.0     2981.107371
9700                  180            NaN       154.0     2439.525729
9701                  220            2.0       138.0     2583.471318
9702                  230            4.0       177.0     2905.527390
9703                  270            3.0       140.0     2908.043477

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive
1             17.8        2007     USA  Gasoline  Front-wheel drive
2             15.1        2018  Europe  Gasoline  Front-wheel drive
3             20.2        2009     USA    Diesel    All-wheel drive
4             14.4        2009  Europe  Gasoline    All-wheel drive
...            ...         ...     ...       ...                ...
9699          17.3        2013  Europe    Diesel  Front-wheel drive
9700          15.0        2004     USA  Gasoline    All-wheel drive
9701          15.1        2008     USA    Diesel    All-wheel drive
9702          19.4        2011     USA    Diesel  Front-wheel drive
9703          14.7        2005    Asia    Diesel    All-wheel drive

      num_doors  fuel_efficiency_mpg
0           0.0            13.231729
1           0.0            13.688217
2           0.0            14.246341
3           2.0            16.912736
4           2.0            12.488369
...         ...                  ...
9699        NaN            15.101802
9700        0.0            17.962326
9701       -1.0            17.186587
9702        1.0            15.331551
9703       -1.0            14.884467

[9704 rows x 11 columns]>